version: "3.8"

services:
  nexy-mcp:
    platform: linux/amd64
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    restart: unless-stopped
